/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package audit_management;

import net.sf.jasperreports.engine.*;
//import net.sf.jasperreports.engine.export.*;
//import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;

public class DeputyCommissionerWindow extends javax.swing.JFrame {
    Login lg = new Login();
    //Create a reference to the DeputyCommissionerHamdler window.
    DeputyCommissionerHandler newHandler = new DeputyCommissionerHandler();
    DeputyCommissionerHandler handler;
    boolean searched = false;
    
    public DeputyCommissionerWindow() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        ReceiptTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        textPaymentID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textPaymentDate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textPaymentAmmount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textPaymentType = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textPaymentDescription = new javax.swing.JTextField();
        btnGetPayment = new javax.swing.JButton();
        btnPrintPayment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnGetReceipt = new javax.swing.JButton();
        btnPrintReceipt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textReceiptID = new javax.swing.JTextField();
        textReceiptDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textReceiptAmmount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textReceiptType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textReceiptDescription = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textEmployeeID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textLastName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textJobTitle = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textSalary = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textOtherDetails = new javax.swing.JTextField();
        btnGetEmployee = new javax.swing.JButton();
        btnPrintEmployee = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deputy Commissioner");

        ReceiptTab.setBackground(new java.awt.Color(204, 204, 204));
        ReceiptTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        ReceiptTab.setToolTipText("Just enter the payment's ID and press this button");
        ReceiptTab.setFont(new java.awt.Font("Times New Roman", 1, 24));

        textPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaymentIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setText("Payment ID");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setText("Date (yy:mm:dd)");

        textPaymentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaymentDateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel18.setText("Ammount (Rs.)");

        textPaymentAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaymentAmmountActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel19.setText("Type");

        textPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaymentTypeActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel20.setText("Description");

        textPaymentDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaymentDescriptionActionPerformed(evt);
            }
        });

        btnGetPayment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGetPayment.setText("Search");
        btnGetPayment.setToolTipText("Just enter the payment's ID and press this button");
        btnGetPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPaymentActionPerformed(evt);
            }
        });

        btnPrintPayment.setFont(new java.awt.Font("Times New Roman", 1, 14));
        btnPrintPayment.setText("Print Report");
        btnPrintPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textPaymentType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnGetPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                            .addComponent(btnPrintPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textPaymentDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addComponent(textPaymentAmmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addComponent(textPaymentDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addComponent(textPaymentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaymentAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaymentDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrintPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        ReceiptTab.addTab("Payments", jPanel2);

        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14));

        btnGetReceipt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGetReceipt.setText("Search");
        btnGetReceipt.setToolTipText("Just enter the receipt's ID and press this button");
        btnGetReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetReceiptActionPerformed(evt);
            }
        });

        btnPrintReceipt.setFont(new java.awt.Font("Times New Roman", 1, 14));
        btnPrintReceipt.setText("Print Report");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setText("Receipt ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setText("Date (yy:mm:dd)");

        textReceiptID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textReceiptIDActionPerformed(evt);
            }
        });

        textReceiptDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textReceiptDateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel11.setText("Ammount (Rs.)");

        textReceiptAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textReceiptAmmountActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel12.setText("Type");

        textReceiptType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textReceiptTypeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel13.setText("Description");

        textReceiptDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textReceiptDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGetReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textReceiptType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textReceiptDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textReceiptAmmount, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textReceiptDescription)
                    .addComponent(textReceiptID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textReceiptID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textReceiptAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textReceiptType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textReceiptDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ReceiptTab.addTab("Receipts", jPanel1);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setText("Employee's ID");

        textEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel10.setText("First Name");

        textFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFirstNameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel14.setText("Last Name");

        textLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLastNameActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel21.setText("Job Title");

        textJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJobTitleActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel22.setText("Salary (Rs.)");

        textSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSalaryActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel23.setText("Branch");

        textOtherDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOtherDetailsActionPerformed(evt);
            }
        });

        btnGetEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGetEmployee.setText("Search");
        btnGetEmployee.setToolTipText("Just enter the Employee's ID and press this button");
        btnGetEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetEmployeeActionPerformed(evt);
            }
        });

        btnPrintEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14));
        btnPrintEmployee.setText("Print Report");
        btnPrintEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(textSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGetEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addComponent(btnPrintEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(textEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(textLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addComponent(textJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addComponent(textOtherDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOtherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrintEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ReceiptTab.addTab("Employees", jPanel3);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceiptTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoutButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ReceiptTab, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ReceiptTab.getAccessibleContext().setAccessibleName("Receipts");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //The following method executes the function of search button of receipt tab
    private void btnGetReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetReceiptActionPerformed
        String stringID = textReceiptID.getText();
        if(textReceiptID.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please Enter a valid ID");
            return;
        }
        int ID = Integer.parseInt(stringID);
        newHandler.getReceipt(ID);
       
        if(newHandler.getReceiptErrorMsg() != null){
            JOptionPane.showMessageDialog(rootPane, newHandler.getReceiptErrorMsg());
        }
        textReceiptID.setText(Integer.toString(newHandler.getReceiptID()));
        textReceiptDate.setText(newHandler.getReceiptDate());
        textReceiptAmmount.setText(Double.toString(newHandler.getReceiptAmmount()));
        textReceiptType.setText(newHandler.getReceiptType());
        textReceiptDescription.setText(newHandler.getReceiptDescription());
        searched = true;
   }//GEN-LAST:event_btnGetReceiptActionPerformed
   //The following method performs the function of printReport button
    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        
       if(searched == false){
            JOptionPane.showMessageDialog(rootPane, "Please Perform a search on database first.");
            return;
        }
        try {
            String report = "IReports\\ReceiptReport.jrxml";
            JasperReport jReport = JasperCompileManager.compileReport(report);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, newHandler.getConnector());
            JasperViewer.viewReport(jPrint, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    private void textReceiptIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textReceiptIDActionPerformed
       // R_Name = ReceiptName.getText();
    }//GEN-LAST:event_textReceiptIDActionPerformed

    private void textReceiptDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textReceiptDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textReceiptDateActionPerformed

    private void textReceiptAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textReceiptAmmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textReceiptAmmountActionPerformed

    private void textReceiptTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textReceiptTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textReceiptTypeActionPerformed

    private void textReceiptDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textReceiptDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textReceiptDescriptionActionPerformed

    private void textPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaymentIDActionPerformed

    private void textPaymentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaymentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaymentDateActionPerformed

    private void textPaymentAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaymentAmmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaymentAmmountActionPerformed

    private void textPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaymentTypeActionPerformed

    private void textPaymentDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaymentDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPaymentDescriptionActionPerformed
    //This method executes the function of search button of payment window
    private void btnGetPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPaymentActionPerformed
        String stringID = textPaymentID.getText();
        if(textPaymentID.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please Enter a valid ID");
            return;
        }
        int ID = Integer.parseInt(stringID);
        newHandler.getPayment(ID);
       
        if(newHandler.getPaymentErrorMsg() != null){
            JOptionPane.showMessageDialog(rootPane, newHandler.getPaymentErrorMsg());
        }
        textPaymentID.setText(Integer.toString(newHandler.getPaymentID()));
        textPaymentDate.setText(newHandler.getPaymentDate());
        textPaymentAmmount.setText(Double.toString(newHandler.getPaymentAmmount()));
        textPaymentType.setText(newHandler.getPaymentType());
        textPaymentDescription.setText(newHandler.getPaymentDescription());  
        searched = true;
    }//GEN-LAST:event_btnGetPaymentActionPerformed
    //This method executes the function of print button of payment window.
    private void btnPrintPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPaymentActionPerformed
        if(searched == false){
            JOptionPane.showMessageDialog(rootPane, "Please Perform a search on database first.");
            return;
        }
        try {
            String report = "IReports\\PaymentReport.jrxml";
            JasperReport jReport = JasperCompileManager.compileReport(report);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, newHandler.getConnector());
            JasperViewer.viewReport(jPrint, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }          
    }//GEN-LAST:event_btnPrintPaymentActionPerformed

    private void textEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeIDActionPerformed

    private void textFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameActionPerformed

    private void textLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLastNameActionPerformed

    private void textJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJobTitleActionPerformed

    private void textSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSalaryActionPerformed

    private void textOtherDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOtherDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOtherDetailsActionPerformed
    //This method executes the function of search button of Employee tab
    private void btnGetEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetEmployeeActionPerformed
        String stringID = textEmployeeID.getText();
        if(textEmployeeID.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please Enter a valid ID");
            return;
        }
        int ID = Integer.parseInt(stringID);
        newHandler.getEmployee(ID);
       
        if(newHandler.getErrorMsg() != null){
            JOptionPane.showMessageDialog(rootPane, newHandler.getErrorMsg());
        }
        textEmployeeID.setText(Integer.toString(newHandler.getEmployeeID()));
        textFirstName.setText(newHandler.getEmployeeFirstName());
        textLastName.setText(newHandler.getEmployeeLastName());
        textJobTitle.setText(newHandler.getJobTitle());
        textSalary.setText(Double.toString(newHandler.getSalary()));
        textOtherDetails.setText(newHandler.getOtherDetails());
        searched = true;
    }//GEN-LAST:event_btnGetEmployeeActionPerformed
    //The function of print button of Employee tab
    private void btnPrintEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintEmployeeActionPerformed
        if(searched == false){
            JOptionPane.showMessageDialog(rootPane, "Please Perform a search on database first.");
            return;
        }
        try {
            String report = "IReports\\Employee.jrxml";
            JasperReport jReport = JasperCompileManager.compileReport(report);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, newHandler.getConnector());
            JasperViewer.viewReport(jPrint, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnPrintEmployeeActionPerformed
    //The function of the logout button
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        //Leaves the DeputyCommissionerWindow and open the Login window
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeputyCommissionerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeputyCommissionerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeputyCommissionerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeputyCommissionerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeputyCommissionerWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTabbedPane ReceiptTab;
    private javax.swing.JButton btnGetEmployee;
    private javax.swing.JButton btnGetPayment;
    private javax.swing.JButton btnGetReceipt;
    private javax.swing.JButton btnPrintEmployee;
    private javax.swing.JButton btnPrintPayment;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textEmployeeID;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textJobTitle;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textOtherDetails;
    private javax.swing.JTextField textPaymentAmmount;
    private javax.swing.JTextField textPaymentDate;
    private javax.swing.JTextField textPaymentDescription;
    private javax.swing.JTextField textPaymentID;
    private javax.swing.JTextField textPaymentType;
    private javax.swing.JTextField textReceiptAmmount;
    private javax.swing.JTextField textReceiptDate;
    private javax.swing.JTextField textReceiptDescription;
    private javax.swing.JTextField textReceiptID;
    private javax.swing.JTextField textReceiptType;
    private javax.swing.JTextField textSalary;
    // End of variables declaration//GEN-END:variables
}
